<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>DeepSeekClock.Windows</RootNamespace>
    <AssemblyName>DeepSeekClock</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationIcon>Resources\deepseek_256.ico</ApplicationIcon>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\deepseek_256.ico">
      <LogicalName>deepseek_256.ico</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DeepSeekClock.Core\DeepSeekClock.Core.csproj" />
  </ItemGroup>
</Project>
